# Generated by Django 3.2.7 on 2021-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_squashed_0009_artworkevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkevent',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artworkevent',
            name='to_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
