# Generated by Django 3.2.7 on 2021-10-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artwork_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.PositiveBigIntegerField(db_index=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=64)),
                ('seller', models.CharField(blank=True, max_length=64, null=True)),
                ('buyer', models.CharField(blank=True, max_length=64, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.artwork')),
            ],
        ),
    ]
