# Generated by Django 3.2.7 on 2021-11-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_salelisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejaculation_tx', models.CharField(db_index=True, max_length=128)),
                ('ejaculation_confirmed', models.BooleanField(default=False)),
                ('ovulation_tx', models.CharField(db_index=True, max_length=128)),
                ('ovulation_confirmed', models.BooleanField(default=False)),
                ('dna', models.BinaryField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_processes', to='app.artwork')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_processes', to='app.profile')),
            ],
        ),
    ]
