# Generated by Django 3.2.7 on 2021-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_generationprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationprocess',
            name='ejaculation_confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='generationprocess',
            name='ovulation_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
